apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-proxy.fullname" . }}
  labels:
    {{- include "helm-proxy.labels" . | nindent 4 }}
data:
  CACHE_TTL: {{ .Values.config.cacheTtl | quote }}
  CACHE_DIR: {{ .Values.config.cacheDir | quote }}
  DEFAULT_REF: {{ .Values.config.defaultRef | quote }}
  EXTERNAL_BASE_URL: {{ .Values.config.externalBaseUrl | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ALLOWED_HOSTS: {{ join "," .Values.config.allowedHosts | quote }}
