{{- if include "helm-proxy.needsSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-proxy.secretName" . }}
  labels:
    {{- include "helm-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.gitCredentials }}
  GIT_CREDENTIALS: {{ .Values.gitCredentials | toJson | quote }}
  {{- end }}
  {{- if .Values.refreshToken }}
  REFRESH_TOKEN: {{ .Values.refreshToken | quote }}
  {{- end }}
{{- end }}
